language: python
python:
  - "3.4"

#
# Command to install dependencies.
#
install:
  - pip install coveralls
  - pip install -r test-requirements.txt

before_script: cd tests
#
# Run tests + coverage.
#
script: py.test --cov-config ../.coveragerc --cov-report= --cov=..

#
# Send coverage report to coveralls.io
#
after_success:
  - coveralls

notifications:
    email: false
