##############################################################################
# HDX DATA FRESHNESS:
#
#  Database:
#   - PostgreSQL
#
#  Program:
#   - HDX Data Freshness: for collecting freshness statistics about HDX.
#
##############################################################################

version: "3"

services:
  #
  # Database
  #
  db:
    image: unocha/alpine-base-postgres:201010-PR90
    environment:
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
    volumes:
      - "$DB_VOL_BASE_PATH/freshness-db:/var/lib/pgsql"
      - "./docker/db-opt:/opt/db"

  #
  # REST api
  #
  rest:
    image: mcarans/alpine-haskell-postgrest
    ports:
      - "3000"
    environment:
      - DB_URL=${DB_URL}

  #
  # Program
  #
  app:
    image: mcarans/hdx-data-freshness
    hostname: hdx-data-freshness
    volumes:
      - "/:/srv"
    environment:
      - DB_URL=${DB_URL}
    command: python3 -m freshness
