##############################################################################
# HDX DATA FRESHNESS:
#
#  Database:
#   - PostgreSQL
#
#  Program:
#   - HDX Data Freshness: for collecting freshness statistics about HDX.
#
##############################################################################

version: "2"

services:
  #
  # Database
  #
  db:
    image: unocha/alpine-base-postgres

  #
  # Program
  #
  hdx-data-freshness:
    build: .
    volumes:
      - "./:/hdx-data-freshness"
    # if you need any port from the container
    #ports:
    #  - "8080:80"

