
POSTGRESQL_USER=${DB_USER:-"docker"}
POSTGRESQL_PASS=${DB_PASS:-"docker"}
POSTGRESQL_DB=${DB_NAME:-"docker"}

su - postgres -c "psql -c \" \
CREATE USER $POSTGRESQL_USER WITH SUPERUSER;;\""
su - postgres -c "psql -c \" \
ALTER USER $POSTGRESQL_USER WITH PASSWORD '$POSTGRESQL_PASS';\""
su - postgres -c "psql -c \" \
CREATE DATABASE $POSTGRESQL_DB OWNER $POSTGRESQL_USER;\""
